import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Twitter-3.0v</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<h1>Tacy Kaindaaa</h1>
   
    </div>
  )
}
