import Head from 'next/head'
import Sidebar from "../components/Sidebar";
import 'tailwindcss/tailwind.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Twitter-3.0v</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-7xl mx-auto ">
{/*Sidebar*/}
<Sidebar/>
{/*feed*/}
{/*widgets*/}
{/*model*/}
      </main>

   
    </div>
  )
}
